name: Mutation Tests (PIT)

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: mutation-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pit:
    name: Run PIT mutation tests
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '23'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Build & compile tests
        run: |
          mvn -B clean compile test-compile

      - name: Run PIT
        run: |
          mvn -B org.pitest:pitest-maven:mutationCoverage

      - name: Upload PIT report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pit-reports
          path: |
            **/target/pit-reports/**
          if-no-files-found: warn
